accordion goated mode part 2
KnightHacks/knighthacks pull request #62
Opened 2024-06-27 23:22 UTC by DVidal1205

i really hope this works
- adds shadcnui accordions for some nice animations and centers text
![image](https://github.com/KnightHacks/knighthacks/assets/111909137/82a829b3-82e3-46bb-927e-3eaa3d985e89)

2024-06-28 00:18 UTC, LightBounded requested changes
Need to pull from ui package instead of creating your components

2024-06-28 00:18 UTC, LightBounded commented on apps/2024/src/app/(main)/_components/ui/accordion.tsx
Can u put this component in the ui package

2024-06-28 00:18 UTC, LightBounded commented on apps/2024/src/lib/utils.ts
This is already defined in our ui package

2024-06-28 00:18 UTC, LightBounded commented on apps/2024/tailwind.config.ts
Dont need this, since we'll be using our ui package

2024-06-28 00:22 UTC, DVidal1205 commented on apps/2024/src/app/(main)/_components/ui/accordion.tsx
I'm getting errors now 
![image](https://github.com/KnightHacks/knighthacks/assets/111909137/c22b1c5f-b5e1-47ab-8908-21e512bd529c)

2024-06-28 00:23 UTC, DVidal1205 commented on apps/2024/src/app/(main)/_components/ui/accordion.tsx
wait nvm im cooked one sec

2024-06-29 03:09 UTC, LightBounded commented on apps/2024/tailwind.config.ts
Can you add this file back. It should look like this:
```
import type { Config } from "tailwindcss";
import baseConfig from "@knighthacks/tailwind-config/web";

export default {
  // We need to append the path to the UI package to the content array so that
  // those classes are included correctly.
  content: [...baseConfig.content, "../../packages/ui/**/*.{ts,tsx}"],
  presets: [baseConfig],
  theme: {},
} satisfies Config;
```

2024-06-29 03:10 UTC, LightBounded commented on apps/2024/components.json
We don't need this file since we'll be pulling components from the ui package.

2024-06-29 03:11 UTC, LightBounded requested changes, later dismissed

2024-06-29 03:11 UTC, LightBounded commented on apps/2024/tailwind.config.ts
Can you add this back?

2024-06-29 22:20 UTC, gitSean23 approved these changes
lgtm! :)

2024-06-29 22:37 UTC, closed without merging